import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
<<<<<<< HEAD
import { ThemeProvider } from '@/components/theme-provider';
import Navbar from '@/components/navbar';
import Footer from '@/components/footer';
import { Toaster } from '@/components/ui/toaster';
import { CartProvider } from '@/contexts/cart-context';
import { AuthProvider } from '@/contexts/auth-context';
=======
>>>>>>> add-to-cart-checkout-page

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
<<<<<<< HEAD
  title: 'NomNow - Food Ordering System',
  description: 'Order your favorite food from local restaurants',
=======
  title: 'Create Next App',
  description: 'Generated by create next app',
>>>>>>> add-to-cart-checkout-page
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
<<<<<<< HEAD
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            <CartProvider>
              <div className="flex flex-col min-h-screen">
                <Navbar />
                <main className="flex-grow">{children}</main>
                <Footer />
              </div>
              <Toaster />
            </CartProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
=======
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
>>>>>>> add-to-cart-checkout-page
